/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Famicomlink (https://sketchfab.com/Famifawx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nes-cartridge-9fe6d3a14db9484eb3b7b7387a49ebcd
Title: NES Cartridge
*/

import React, { useRef  } from "react";
import { useGLTF, useTexture, Decal } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { a } from "@react-spring/three";


const Cartridge = (props) => {
  const { nodes, materials } = useGLTF("nes_cartridge.glb");
  const cartridgeRef = useRef();
  const texture = useTexture(props.cover);
  const rotationFactor = 0.003;

  const rotate = () => {
    cartridgeRef.current.rotation.y += rotationFactor * Math.PI;
    if (cartridgeRef.current.rotation.y >= Math.Pi *2) {
      cartridgeRef.current.rotation.y = cartridgeRef.current.rotation.y - (Math.Pi * 2);
    }
  }

  useFrame(() => {
    rotate();
  });


  return (
    <a.group ref={cartridgeRef} {...props}>
      <group scale={0.015}>
        <group
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <mesh
            castShadow
            geometry={nodes.Cube_Material_0.geometry}
            material={materials.Material}
          />

          {/* Cover Image */}
          <mesh
            geometry={nodes.Cube_Material001_0.geometry}
            // material={materials["Material.001"]}
          >
            <meshBasicMaterial transparent opacity={0} />
            <Decal
                // debug // Makes "bounding box" of the decal visible
                position={[-0.5, 0, -0.85]} // Position of the decal
                rotation={[Math.PI / 2, 0, -Math.PI]} // Rotation of the decal (can be a vector or a degree in radians)
                scale={[1.8, 2.8, 1]} // Scale of the decal
            >
                <meshBasicMaterial
                map={texture}
                polygonOffset
                polygonOffsetFactor={-1} // The material should take precedence over the original
                />
            </Decal>
          </mesh>
        </group>
      </group>
    </a.group>
  );
}

export default Cartridge;