import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/components/Navbar';
import web3Onboard from './utils/web3-onboard';
import { Web3OnboardProvider } from '@web3-onboard/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'World Arcade',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Web3OnboardProvider web3Onboard={web3Onboard}>
        <body className={inter.className}>
          <Navbar></Navbar>
          {children}
        </body>
      </Web3OnboardProvider>
    </html>
  )
}
