import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/components/Navbar';
import {Web3OnboardProviderClient} from './utils/web3OnboardProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'World Arcade',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Web3OnboardProviderClient>
        <body className={inter.className}>
          <Navbar></Navbar>
          {children}
        </body>
      </Web3OnboardProviderClient>
    </html>
  )
}
