/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  IndexerOutput: IndexerOutput;
  IndexerPayload: IndexerPayload;
}
export interface IndexerOutput {
  data: OutputIndex[];
}
export interface OutputIndex {
  output_type: string;
  module: string;
  class_name: string;
  input_index: number;
  output_index: number;
}
export interface IndexerPayload {
  tags?: string[];
  output_type?: string;
  msg_sender?: string;
  timestamp_gte?: number;
  timestamp_lte?: number;
  module?: string;
  input_index?: number;
}
