/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  IndexerPayload: IndexerPayload;
  IndexerOutput: IndexerOutput;
}
export interface IndexerPayload {
  tags?: string[];
  type?: string;
  msg_sender?: string;
  timestamp_gte?: number;
  timestamp_lte?: number;
  module?: string;
  input_index?: number;
  order_by?: string;
  order_dir?: string;
  page?: number;
  page_size?: number;
}
export interface IndexerOutput {
  data: OutputIndex[];
  total: number;
  page: number;
}
export interface OutputIndex {
  type: string;
  module: string;
  class_name: string;
  input_index: number;
  output_index?: number;
}
